version: 2
updates:
  # Composer (dépendances PHP)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # npm/yarn (assets front)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # GitHub Actions (CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
