endroid_qr_code:
    # Depuis la version 7 du bundle, chaque configuration nommée se place sous "builders".
    builders:
        default:
            writer: Endroid\QrCode\Writer\PngWriter
            size: 300
            margin: 10
            encoding: 'UTF-8'
            error_correction_level: 'low'
            round_block_size_mode: 'margin'
            validate_result: false
