# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  session: true
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks: ['fr']
  #esi: true
  #fragments: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file

when@dev:
  web_profiler:
    toolbar: false
    intercept_redirects: false
  framework:
    profiler:
      enabled: false
      collect: false
