services:
  reverse-proxy:
    image: ghcr.io/joel-sudo-design/cinephoria_web/caddy:${APP_TAG}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [web, backend]
    depends_on:
      - app

  app:
    image: ghcr.io/joel-sudo-design/cinephoria_web/app:${APP_TAG}
    restart: unless-stopped
    environment:
      APP_ENV: prod
      DATABASE_URL: ${DATABASE_URL}
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_DB: ${MONGODB_DB}
      MAILER_DSN: ${MAILER_DSN}
      JWT_SECRET_KEY: /var/www/Cinephoria_web/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/Cinephoria_web/config/jwt/public.pem
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      JWT_TOKEN_TTL: ${JWT_TOKEN_TTL:-3600}
    volumes:
      - jwt_keys:/var/www/Cinephoria_web/config/jwt:ro
    depends_on:
      db:
        condition: service_started
      mongo:
        condition: service_started
    networks: [backend]

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks: [backend]

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
      ME_USER: ${ME_USER}
      ME_PASS: ${ME_PASS}
    volumes:
      - mongodb_data:/data/db
      - ./001-user.js:/docker-entrypoint-initdb.d/001-user.js:ro
    networks: [ backend ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    networks: [backend]
    ports:
      - "127.0.0.1:8081:80"

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASS}
    networks: [backend]
    ports:
      - "127.0.0.1:8082:8081"
    depends_on:
      - mongo

networks:
  web: {}
  backend: {}

volumes:
  db_data: {}
  mongodb_data: {}
  caddy_data: {}
  caddy_config: {}
  jwt_keys: {}
