services:
  reverse-proxy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [web]

  app:
    image: ghcr.io/joel-sudo-design/cinephoria_web/app:${APP_TAG:-latest}
    restart: unless-stopped
    environment:
      APP_ENV: prod
      DATABASE_URL: ${DATABASE_URL}
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_DB: ${MONGODB_DB}
      MAILER_DSN: ${MAILER_DSN}
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
    networks: [web, backend]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks: [backend]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks: [backend]

  # OUTILS D'ADMIN — accessibles SEULEMENT via tunnel SSH
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    networks: [backend]
    ports:
      - "127.0.0.1:8081:80"   # http://localhost:8081 via tunnel

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASS}
    networks: [backend]
    ports:
      - "127.0.0.1:8082:8081" # http://localhost:8082 via tunnel
    depends_on:
      - mongo

networks:
  web: {}
  backend: {}

volumes:
  db_data: {}
  mongodb_data: {}
  caddy_data: {}
  caddy_config: {}
