services:
  app:
    volumes:
      - public_build:/var/www/Cinephoria_web/public/build

  reverse-proxy:
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - ./public:/var/www/Cinephoria_web/public:ro
      - public_build:/var/www/Cinephoria_web/public/build:ro
    networks:
      - web
      - backend

volumes:
  public_build:
